// qiankunProject/sub-app-c/src/pages/Edit.jsx
import React from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import { mergeQueryParams, toQueryString } from '../utils/queryHelper';

// 页面内联样式
const styles = {
  container: { padding: '20px' },
  title: { color: '#52c41a', marginBottom: '16px' },
  info: { lineHeight: '2', fontSize: '14px' },
  btn: { padding: '4px 12px', cursor: 'pointer', border: '1px solid #52c41a', background: '#52c41a', color: '#fff', borderRadius: '4px', marginTop: '16px' }
};

/**
 * 编辑页组件
 */
function Edit() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();

  // 从 URL 获取参数
  const id = searchParams.get('id');
  const source = searchParams.get('source');
  const userId = searchParams.get('userId');

  /**
   * 返回列表页，保留主应用传入的参数
   */
  const goBack = () => {
    const query = toQueryString(mergeQueryParams({}));
    navigate(`/${query}`);
  };

  return (
    <div style={styles.container}>
      <h2 style={styles.title}>子应用 C - 编辑页</h2>
      <div style={styles.info}>
        <p>编辑记录 ID：{id}</p>
        <p>来源（主应用参数）：{source}</p>
        <p>用户 ID（主应用参数）：{userId}</p>
      </div>
      <button style={styles.btn} onClick={goBack}>返回列表</button>
    </div>
  );
}

export default Edit;

// qiankunProject/sub-app-d/src/pages/Edit.vue
<template>
  <!-- 编辑页 -->
  <div class="edit-page">
    <h2>子应用 D - 编辑页</h2>
    <div class="info">
      <p>编辑记录 ID：{{ id }}</p>
      <p>来源（主应用参数）：{{ source }}</p>
      <p>用户 ID（主应用参数）：{{ userId }}</p>
    </div>
    <button class="btn" @click="goBack">返回列表</button>
  </div>
</template>

<script>
import { useRoute, useRouter } from 'vue-router';
import { mergeQueryParams, toQueryString } from '../utils/queryHelper';

export default {
  name: 'Edit',
  setup() {
    const route = useRoute();
    const router = useRouter();

    // 从 URL 获取参数
    const id = route.query.id;
    const source = route.query.source;
    const userId = route.query.userId;

    /**
     * 返回列表页，保留主应用传入的参数
     */
    const goBack = () => {
      const query = toQueryString(mergeQueryParams({}));
      router.push(`/${query}`);
    };

    return { id, source, userId, goBack };
  }
};
</script>

<style scoped>
/* 编辑页样式 */
.edit-page {
  padding: 20px;
}

.edit-page h2 {
  color: #ff7a45;
  margin-bottom: 16px;
}

.info {
  line-height: 2;
  font-size: 14px;
}

.btn {
  padding: 4px 12px;
  cursor: pointer;
  border: 1px solid #ff7a45;
  background: #ff7a45;
  color: #fff;
  border-radius: 4px;
  margin-top: 16px;
}
</style>
